"""initial migration

Revision ID: e9c79f16d58d
Revises: None
Create Date: 2016-05-26 02:55:40.591476

"""

# revision identifiers, used by Alembic.
revision = 'e9c79f16d58d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('title', sa.CHAR(), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=40), nullable=True),
    sa.Column('time_created', sa.VARCHAR(length=40), nullable=True),
    sa.Column('author', sa.VARCHAR(length=40), nullable=True),
    sa.Column('viewed', sa.Integer(), nullable=True),
    sa.Column('remarked', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('imgs', sa.Text(), nullable=True),
    sa.Column('play_url', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    ### end Alembic commands ###
